import { Space_Grotesk } from 'next/font/google';
import './globals.css';

// =========  components to header and footer imported
import HeaderCompo from './_components/Header';
import Footer from './_components/Footer';

const SpaceGrotesk = Space_Grotesk({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={SpaceGrotesk.className}>
        <header>
          <div className="md:px-8 lg:px-20 xl:px-60">
            <HeaderCompo></HeaderCompo>
          </div>
        </header>

        {children}
        {/* ======= Footer */}
        <Footer></Footer>
      </body>
    </html>
  );
}
